### ISSUE TITLE
Приложение "15_selenium_web_driver " не отправляет автоматический отклик на вакансию.

### ISSUE THREAD

**Issue by Alewka123** [iampopovich/routine_python#5]

**Comment by Alewka123** [comment]
**Содержимое файла cred.cnfg:**

> {"login":"****",
> "password":"****",
> "resumeID":"2c3161aaff059ece090039ed1f76376a744148",
> "browserPath":"C:\Arduino\chromedriver.exe"
> "reply":"1",
> "replyMessage":"Уважаемый рекрутер!"
> }

При запуске через консоль выдает ошибку:

> C:\Users\Алексей>python cv_updater.py
>   File "cv_updater.py", line 34
>     def send_reply(browser, config):
>                                    ^
> IndentationError: unindent does not match any outer indentation level
> 
> 
 При комментировании функции отправки в коде программы  строки с 34 по 61 выдает следующую ошибку:

> C:\Users\Алексей>python cv_updater.py
> Traceback (most recent call last):
>   File "cv_updater.py", line 81, in main
>     config = get_config()
>   File "cv_updater.py", line 9, in get_config
>     config = json.load(c)
>   File "C:\Users\Алексей\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "C:\Users\Алексей\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "C:\Users\Алексей\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\Users\Алексей\AppData\Local\Programs\Python\Python38-32\lib\json\decoder.py", line 353, in raw_decode
>     obj, end = self.scan_once(s, idx)
> json.decoder.JSONDecodeError: Invalid \escape: line 4 column 18 (char 119)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "cv_updater.py", line 94, in <module>
>     main()
>   File "cv_updater.py", line 89, in main
>     browser.quit()
> UnboundLocalError: local variable 'browser' referenced before assignment

**Comment by iampopovich** [comment]
fixed with set calling send_reply under comment - it'll be fixed in next versions.
1) make sure your config file has .cfg extension
2) copy repository or make "git pull" from directory with your local repository copy
3) try to run it again

**Comment by iampopovich** [comment]
fixed
